[package]
name = "vidool"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk = "^0.15.0"
glib = "0.15.6"
relm = "^0.23.0"
relm-derive = "^0.23.0"
gstreamer = "0.18.5"
